name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build11111111,
        echo test, and deploy your project.
        echo $SIGN | awk '{print substr($0,0,length-1)}'
        echo $SIGN | awk '{print substr($0,2,length)}'
        echo test
      env:
        GITHUB_TOKEN: ${{ secrets.SIGN }}

